-- Generated by scripts/sync-supabase-migration.cjs.
-- Edit docs/supabase/schema.sql, then run npm run supabase:migration:sync.

-- Project Odysseus initial Supabase LMS schema plan.
-- This is additive planning SQL for a Supabase project, not yet wired into the existing Prisma migrations.

create extension if not exists "pgcrypto";

-- Postgres has no `create type ... if not exists`; guarded via pg_type check
-- (matches this file's established guarded-enum convention) so this file can
-- be safely re-applied against an already-migrated database, not just a fresh one.
do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type public.user_role as enum ('student', 'tutor', 'admin', 'parent', 'ngo_partner');
  end if;
  if not exists (select 1 from pg_type where typname = 'record_status') then
    create type public.record_status as enum ('active', 'inactive', 'pending', 'approved', 'suspended');
  end if;
  if not exists (select 1 from pg_type where typname = 'assignment_status') then
    create type public.assignment_status as enum ('draft', 'published', 'closed', 'archived');
  end if;
  if not exists (select 1 from pg_type where typname = 'submission_status') then
    create type public.submission_status as enum ('not_submitted', 'submitted', 'marked', 'returned');
  end if;
  if not exists (select 1 from pg_type where typname = 'payment_status') then
    create type public.payment_status as enum ('pending', 'paid', 'overdue', 'voided');
  end if;
end
$$;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null unique,
  phone text,
  role public.user_role not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ngo_partners (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contact_person text,
  contact_email text,
  contact_phone text,
  location text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  grade text,
  school text,
  parent_name text,
  parent_contact text,
  ngo_partner_id uuid references public.ngo_partners(id),
  status public.record_status not null default 'pending',
  created_at timestamptz not null default now()
);

-- Production's students table (created before this file's current definition
-- existed) carries several extra columns not modeled here at all --
-- full_name, guardian_name/phone/relationship/email/address, notes,
-- subjects_json, partner_affiliation -- leftovers from an earlier schema
-- iteration, since profiles.full_name is this schema's actual source of
-- truth for a person's name. Only full_name was NOT NULL with no default,
-- which silently blocked every insert into students (nothing had actually
-- attempted a new students row anywhere in this migration until
-- admin-invite-user's functional verification surfaced it -- the table had
-- zero rows in production, so this is a pure constraint fix, not a backfill).
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'students' and column_name = 'full_name' and is_nullable = 'NO'
  ) then
    alter table public.students alter column full_name drop not null;
  end if;
end
$$;

create table if not exists public.student_career_profiles (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null unique references public.students(id) on delete cascade,
  interests_json jsonb not null default '[]'::jsonb,
  preferred_subjects_json jsonb not null default '[]'::jsonb,
  target_careers_json jsonb not null default '[]'::jsonb,
  aps_target integer check (aps_target is null or (aps_target >= 0 and aps_target <= 60)),
  saved_careers_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tutors (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  subjects text[] not null default '{}',
  grades text[] not null default '{}',
  hourly_rate numeric(12, 2),
  status public.record_status not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  grade text,
  curriculum text,
  unique (name, grade, curriculum)
);

create table if not exists public.assignments (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  subject_id uuid references public.subjects(id),
  grade text,
  due_date timestamptz,
  created_by uuid references public.profiles(id),
  status public.assignment_status not null default 'draft',
  attachment_url text,
  rubric_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.guardians (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid references public.profiles(id) on delete set null,
  full_name text not null,
  email text,
  phone text,
  communication_preference text not null default 'email',
  notes text,
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (email)
);

create table if not exists public.student_guardians (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  guardian_id uuid not null references public.guardians(id) on delete cascade,
  relationship_type text not null default 'guardian',
  is_primary boolean not null default false,
  can_receive_reports boolean not null default true,
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, guardian_id)
);

create table if not exists public.assignment_submissions (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null references public.assignments(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  storage_key text,
  file_url text,
  original_filename text,
  mime_type text,
  size_bytes bigint,
  text_answer text,
  submitted_at timestamptz not null default now(),
  status public.submission_status not null default 'submitted',
  version_number integer not null default 1,
  is_latest boolean not null default true,
  marks_awarded numeric(8, 2),
  feedback text,
  rubric_scores_json jsonb not null default '{}'::jsonb,
  marks_released boolean not null default false,
  feedback_released boolean not null default false,
  released_at timestamptz,
  unique (assignment_id, student_id, version_number)
);

create table if not exists public.audit_log (
  id uuid primary key default gen_random_uuid(),
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_role public.user_role,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Backfill for a database where this table was partially created by an
-- earlier, interrupted migration attempt (same reasoning as the
-- assignment_submissions backfill elsewhere in this file).
alter table public.audit_log add column if not exists metadata jsonb not null default '{}'::jsonb;

-- Guarded ALTER (idempotent, matching the privacy_request_type enum guard
-- pattern): alter table ... add constraint has no native IF NOT EXISTS.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'assignment_submissions_marks_range') then
    alter table public.assignment_submissions
      add constraint assignment_submissions_marks_range
      check (marks_awarded is null or (marks_awarded >= 0 and marks_awarded <= 100));
  end if;
end
$$;

alter table public.assignments add column if not exists rubric_json jsonb not null default '[]'::jsonb;
-- These columns are also in the inline CREATE TABLE above, which is a no-op
-- against a database where assignment_submissions already existed before
-- this column set was designed (confirmed live in production: `create table
-- if not exists` skips the WHOLE statement if the table exists at all, it
-- does not add missing columns to an existing table) -- so every column
-- needs its own ADD COLUMN IF NOT EXISTS backfill, not just the four that
-- already had one.
alter table public.assignment_submissions add column if not exists storage_key text;
alter table public.assignment_submissions add column if not exists file_url text;
alter table public.assignment_submissions add column if not exists original_filename text;
alter table public.assignment_submissions add column if not exists mime_type text;
alter table public.assignment_submissions add column if not exists size_bytes bigint;
alter table public.assignment_submissions add column if not exists text_answer text;
alter table public.assignment_submissions add column if not exists version_number integer not null default 1;
alter table public.assignment_submissions add column if not exists is_latest boolean not null default true;
alter table public.assignment_submissions add column if not exists rubric_scores_json jsonb not null default '{}'::jsonb;
alter table public.assignment_submissions add column if not exists marks_released boolean not null default false;
alter table public.assignment_submissions add column if not exists feedback_released boolean not null default false;
alter table public.assignment_submissions add column if not exists released_at timestamptz;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'assignments_rubric_json_array') then
    alter table public.assignments
      add constraint assignments_rubric_json_array
      check (jsonb_typeof(rubric_json) = 'array');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'assignment_submissions_rubric_scores_object') then
    alter table public.assignment_submissions
      add constraint assignment_submissions_rubric_scores_object
      check (jsonb_typeof(rubric_scores_json) = 'object');
  end if;
  -- Size caps (64KB): nothing previously stopped a client from storing a
  -- multi-megabyte rubric/rubric-scores JSON document.
  if not exists (select 1 from pg_constraint where conname = 'assignments_rubric_json_size') then
    alter table public.assignments
      add constraint assignments_rubric_json_size
      check (octet_length(rubric_json::text) < 65536);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'assignment_submissions_rubric_scores_size') then
    alter table public.assignment_submissions
      add constraint assignment_submissions_rubric_scores_size
      check (octet_length(rubric_scores_json::text) < 65536);
  end if;
end
$$;

create table if not exists public.student_progress (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  subject_id uuid references public.subjects(id),
  topic text not null,
  score numeric(5, 2) not null check (score >= 0 and score <= 100),
  cognitive_level text,
  recorded_at timestamptz not null default now(),
  assignment_submission_id uuid references public.assignment_submissions(id) on delete cascade
);

-- Backfill for a pre-existing production table (the inline column above is a
-- no-op there -- see the "Identity lookup shadow table" / assignment_submissions
-- backfill precedent elsewhere in this file for why this second statement is
-- required, not redundant).
alter table public.student_progress add column if not exists assignment_submission_id uuid references public.assignment_submissions(id) on delete cascade;

-- Real bug fix, not a design choice: mark_assignment_submission() used to do
-- a plain INSERT into student_progress every time a submission was (re-)marked,
-- so re-marking the same submission (e.g. 65 -> 70 -> 72) created a new
-- progress row each time instead of updating the one that already represented
-- it, inflating averages/history. This partial unique index lets the RPC
-- upsert on (assignment_submission_id) instead. Partial (not a plain unique
-- constraint) because older progress rows predating this column, or any
-- future non-submission-derived progress entry, legitimately have no
-- assignment_submission_id and must not be forced to collide on NULL.
create unique index if not exists idx_student_progress_submission_unique
  on public.student_progress(assignment_submission_id)
  where assignment_submission_id is not null;

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  amount numeric(12, 2) not null check (amount >= 0),
  payment_type text not null,
  status public.payment_status not null default 'pending',
  due_date date,
  paid_at timestamptz,
  notes text
);

create table if not exists public.tutor_payments (
  id uuid primary key default gen_random_uuid(),
  tutor_id uuid not null references public.tutors(id) on delete cascade,
  amount numeric(12, 2) not null check (amount >= 0),
  payment_period text not null,
  status public.payment_status not null default 'pending',
  paid_at timestamptz,
  notes text
);

create table if not exists public.classes (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Class',
  tutor_id uuid not null references public.tutors(id) on delete cascade,
  subject_id uuid references public.subjects(id),
  grade text,
  location text,
  day_of_week text,
  start_time time,
  end_time time,
  ngo_partner_id uuid references public.ngo_partners(id),
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Guarded ALTER (idempotent, matching the tutors_approval_status_check
-- pattern): nothing previously stopped end_time <= start_time from being saved.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'classes_time_range') then
    alter table public.classes
      add constraint classes_time_range
      check (end_time is null or start_time is null or end_time > start_time);
  end if;
end
$$;

alter table public.classes add column if not exists name text not null default 'Class';
alter table public.classes add column if not exists status public.record_status not null default 'active';
alter table public.classes add column if not exists created_at timestamptz not null default now();
alter table public.classes add column if not exists updated_at timestamptz not null default now();

create table if not exists public.class_enrollments (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  unique (class_id, student_id)
);

create table if not exists public.tutor_student_allocations (
  id uuid primary key default gen_random_uuid(),
  tutor_id uuid not null references public.tutors(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  status public.record_status not null default 'active',
  start_date date,
  end_date date,
  focus_notes text,
  -- Engagement/contract fields folded in from the retired Prisma `Assignment`
  -- model (migration plan §3A). Nullable/additive: no NOT NULL, no backfill.
  -- `rate_override` is the tutor's negotiated pay rate for this engagement and
  -- is tutor/admin-only -- student-facing readers must NOT select it.
  subject_id uuid references public.subjects(id),
  rate_override numeric(12, 2),
  allowed_days_json jsonb,
  allowed_time_ranges_json jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tutor_id, student_id)
);

-- Size caps (64KB): these are admin-set contract fields, but nothing
-- previously stopped an oversized JSON document from being stored regardless.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'tutor_student_allocations_allowed_days_size') then
    alter table public.tutor_student_allocations
      add constraint tutor_student_allocations_allowed_days_size
      check (allowed_days_json is null or octet_length(allowed_days_json::text) < 65536);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'tutor_student_allocations_allowed_time_ranges_size') then
    alter table public.tutor_student_allocations
      add constraint tutor_student_allocations_allowed_time_ranges_size
      check (allowed_time_ranges_json is null or octet_length(allowed_time_ranges_json::text) < 65536);
  end if;
end
$$;

create index if not exists idx_profiles_role on public.profiles(role);
create index if not exists idx_students_ngo_partner on public.students(ngo_partner_id);
create index if not exists idx_guardians_profile on public.guardians(profile_id);
create index if not exists idx_student_guardians_student on public.student_guardians(student_id, status);
create index if not exists idx_student_guardians_guardian on public.student_guardians(guardian_id, status);
create index if not exists idx_student_career_profiles_student_updated on public.student_career_profiles(student_id, updated_at desc);
create index if not exists idx_assignments_due_date on public.assignments(due_date);
create index if not exists idx_assignments_created_by on public.assignments(created_by);
create index if not exists idx_submissions_student on public.assignment_submissions(student_id);
create index if not exists idx_submissions_student_assignment on public.assignment_submissions(student_id, assignment_id);
create index if not exists idx_submissions_assignment_status on public.assignment_submissions(assignment_id, status);
create unique index if not exists idx_submissions_latest_assignment_student
  on public.assignment_submissions(assignment_id, student_id)
  where is_latest;
create index if not exists idx_submissions_assignment_versions
  on public.assignment_submissions(assignment_id, student_id, version_number desc);
create index if not exists idx_audit_log_created_at on public.audit_log(created_at desc);
create index if not exists idx_audit_log_action on public.audit_log(action);
create index if not exists idx_audit_log_entity on public.audit_log(entity_type, entity_id);
create index if not exists idx_audit_log_actor on public.audit_log(actor_user_id);
create index if not exists idx_progress_student_recorded on public.student_progress(student_id, recorded_at desc);
create index if not exists idx_payments_student_status on public.payments(student_id, status);
create index if not exists idx_classes_tutor on public.classes(tutor_id);
create index if not exists idx_classes_status on public.classes(status);
create index if not exists idx_class_enrollments_student on public.class_enrollments(student_id);
create index if not exists idx_class_enrollments_class_status on public.class_enrollments(class_id, status);
create index if not exists idx_tutor_student_allocations_tutor on public.tutor_student_allocations(tutor_id, status);
create index if not exists idx_tutor_student_allocations_student on public.tutor_student_allocations(student_id, status);

alter table public.profiles enable row level security;
alter table public.students enable row level security;
alter table public.guardians enable row level security;
alter table public.student_guardians enable row level security;
alter table public.student_career_profiles enable row level security;
alter table public.tutors enable row level security;
alter table public.ngo_partners enable row level security;
alter table public.subjects enable row level security;
alter table public.assignments enable row level security;
alter table public.assignment_submissions enable row level security;
alter table public.audit_log enable row level security;
alter table public.student_progress enable row level security;
alter table public.payments enable row level security;
alter table public.tutor_payments enable row level security;
alter table public.classes enable row level security;
alter table public.class_enrollments enable row level security;
alter table public.tutor_student_allocations enable row level security;

-- ============================================================================
-- Identity lookup shadow table -- fixes a real "infinite recursion detected in
-- policy for relation ..." bug, not a design choice. Every current_*() helper
-- below used to join straight into public.profiles (and, for
-- current_tutor_id/current_student_id, into public.tutors/public.students
-- too). Confirmed by direct testing against a real local Postgres: ANY access
-- to public.profiles from within evaluating public.profiles's OWN RLS
-- policies recurses -- REGARDLESS of SECURITY DEFINER, the role's BYPASSRLS
-- attribute, or an explicit `set local row_security = off` inside the
-- function (all three were tried and all three still recursed). This is a
-- hard Postgres limitation: a table's RLS policy (or anything it calls, no
-- matter how it's wrapped) must never scan that same table again while its
-- own policy is being evaluated. The recursion cascades further than
-- profiles alone: public.tutors and public.students each had a raw subquery
-- directly on public.profiles in their own "select self" policies, and
-- profiles' own policies read back into students/tutors
-- (profiles_select_allocated_learning_relationship) -- so evaluating
-- tutors'/students' policies could re-enter profiles' policies, which could
-- re-enter tutors/students, recursing there too (confirmed: querying
-- public.tutors or public.students directly as an authenticated role also
-- raised "infinite recursion detected in policy for relation ...").
--
-- The fix: every current_*() helper below now resolves auth_user_id ->
-- profile_id/role from this tiny denormalized table instead of scanning
-- public.profiles. RLS is NOT enabled here at all (not "using (false)" --
-- literally no RLS), and table privileges are revoked from anon/authenticated
-- below, so it is reachable ONLY through these SECURITY DEFINER functions --
-- never a real client read/write path, so there is nothing to protect with
-- RLS in the first place, and nothing left to recurse.
create table if not exists public.profile_identities (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role public.user_role not null
);

create unique index if not exists idx_profile_identities_profile on public.profile_identities(profile_id);

revoke all on public.profile_identities from anon, authenticated;

create or replace function public.sync_profile_identity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    delete from public.profile_identities where profile_id = old.id;
    return old;
  end if;

  insert into public.profile_identities (auth_user_id, profile_id, role)
  values (new.auth_user_id, new.id, new.role)
  on conflict (auth_user_id) do update set
    profile_id = excluded.profile_id,
    role = excluded.role;
  return new;
end;
$$;

drop trigger if exists trg_sync_profile_identity on public.profiles;
create trigger trg_sync_profile_identity
  after insert or update of auth_user_id, role or delete on public.profiles
  for each row execute function public.sync_profile_identity();

-- One-time backfill for any profiles rows that existed before this trigger.
insert into public.profile_identities (auth_user_id, profile_id, role)
select auth_user_id, id, role from public.profiles
on conflict (auth_user_id) do update set
  profile_id = excluded.profile_id,
  role = excluded.role;

create or replace function public.current_profile_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profile_identities where auth_user_id = auth.uid()
$$;

-- Security fix (2026-07-24): admin RLS/RPC checks used to stop at
-- current_profile_role() = 'admin', matching AUDIT.md's original Critical
-- ("admin session with no server-side MFA") in a new form -- someone who
-- phished an admin's password but not their TOTP device could bypass
-- AdminMfaGate (a React component, not a security boundary) by calling
-- supabase-js/PostgREST directly with an aal1 session. AdminMfaGate remains
-- for UX, but the real enforcement now lives here, in the single function
-- every admin-gated policy/RPC in this file calls. auth.jwt()->>'aal' is
-- absent for the trusted service-role/pg_cron contexts that some RPCs
-- explicitly OR against (e.g. "is_platform_admin() or auth.uid() is null"),
-- so this correctly returns false there rather than raising -- those
-- call sites' own "auth.uid() is null" branch is what grants access.
-- Defined immediately after current_profile_role() (not near its other
-- multi-org helper siblings further down) so every earlier policy/RPC in
-- this file that calls it has a function that actually exists yet --
-- Postgres executes this file's statements in order.
create or replace function public.is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_profile_role() = 'admin'
    and coalesce(auth.jwt() ->> 'aal', 'aal1') = 'aal2'
$$;

create or replace function public.current_profile_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select profile_id from public.profile_identities where auth_user_id = auth.uid()
$$;

create or replace function public.current_student_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select s.id
  from public.students s
  join public.profile_identities pi on pi.profile_id = s.profile_id
  where pi.auth_user_id = auth.uid()
$$;

create or replace function public.current_tutor_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select t.id
  from public.tutors t
  join public.profile_identities pi on pi.profile_id = t.profile_id
  where pi.auth_user_id = auth.uid()
$$;

create or replace function public.can_mark_submission(p_submission_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    public.is_platform_admin()
    or exists (
      select 1
      from public.assignment_submissions sub
      join public.assignments a on a.id = sub.assignment_id
      where sub.id = p_submission_id
        and a.created_by = public.current_profile_id()
        and public.current_profile_role() = 'tutor'
    ),
    false
  )
$$;

create or replace function public.log_audit_event(
  p_action text,
  p_entity_type text,
  p_entity_id text,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_audit_id uuid;
  v_actor_role public.user_role := public.current_profile_role();
begin
  if nullif(btrim(coalesce(p_action, '')), '') is null then
    raise exception 'audit_action_required' using errcode = '23514';
  end if;

  if nullif(btrim(coalesce(p_entity_type, '')), '') is null then
    raise exception 'audit_entity_type_required' using errcode = '23514';
  end if;

  insert into public.audit_log (
    actor_user_id,
    actor_role,
    action,
    entity_type,
    entity_id,
    metadata
  )
  values (
    auth.uid(),
    v_actor_role,
    btrim(p_action),
    btrim(p_entity_type),
    nullif(btrim(coalesce(p_entity_id, '')), ''),
    coalesce(p_metadata, '{}'::jsonb)
  )
  returning id into v_audit_id;

  return v_audit_id;
end;
$$;

create or replace function public.record_audit_event(
  p_action text,
  p_entity_type text,
  p_entity_id text,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role public.user_role := public.current_profile_role();
begin
  if v_role is null then
    raise exception 'audit_actor_required' using errcode = '42501';
  end if;

  if v_role = 'admin' then
    return public.log_audit_event(p_action, p_entity_type, p_entity_id, p_metadata);
  end if;

  -- Security fix (2026-07-24): this used to trust p_entity_id as-is, letting
  -- any tutor forge an assignment.* audit entry for an assignment they don't
  -- own (arbitrary free-text id, never checked against the actual row).
  if v_role = 'tutor'
     and p_action in ('assignment.created', 'assignment.updated', 'assignment.attachment_replaced')
     and exists (
       select 1 from public.assignments a
       where a.id::text = p_entity_id
         and a.created_by = public.current_profile_id()
     )
  then
    return public.log_audit_event(p_action, p_entity_type, p_entity_id, p_metadata);
  end if;

  raise exception 'audit_action_not_allowed' using errcode = '42501';
end;
$$;

create or replace function public.submit_assignment_submission(
  p_assignment_id uuid,
  p_submission_id uuid,
  p_storage_key text,
  p_file_url text,
  p_original_filename text,
  p_mime_type text,
  p_size_bytes bigint,
  p_text_answer text
)
returns table (submission_id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student_id uuid := public.current_student_id();
  v_assignment public.assignments%rowtype;
  v_submission_id uuid := coalesce(p_submission_id, gen_random_uuid());
  v_next_version integer;
  v_text_answer text := nullif(btrim(coalesce(p_text_answer, '')), '');
begin
  if public.current_profile_role() <> 'student' or v_student_id is null then
    raise exception 'only_students_can_submit' using errcode = '42501';
  end if;

  select * into v_assignment
  from public.assignments
  where id = p_assignment_id;

  if not found then
    raise exception 'assignment_not_found' using errcode = 'P0002';
  end if;

  -- Interim check (org check added by a create-or-replace in section 7.5
  -- below, once organization_id/current_student_org_id() exist -- this
  -- function is defined this early in the file so its grant and the
  -- policies that assume it exists work in order).
  if v_assignment.status <> 'published' then
    raise exception 'assignment_not_open_for_submission' using errcode = '42501';
  end if;

  if v_text_answer is null and nullif(p_storage_key, '') is null then
    raise exception 'submission_content_required' using errcode = '23514';
  end if;

  if nullif(p_storage_key, '') is not null and p_storage_key !~ ('^' || v_student_id::text || '/' || p_assignment_id::text || '/' || v_submission_id::text || '/submission\.[A-Za-z0-9]+$') then
    raise exception 'invalid_submission_storage_path' using errcode = '42501';
  end if;

  perform pg_advisory_xact_lock(hashtext(p_assignment_id::text || ':' || v_student_id::text));

  select coalesce(max(version_number), 0) + 1
  into v_next_version
  from public.assignment_submissions
  where assignment_id = p_assignment_id
    and student_id = v_student_id;

  update public.assignment_submissions
  set is_latest = false
  where assignment_id = p_assignment_id
    and student_id = v_student_id
    and is_latest = true;

  insert into public.assignment_submissions (
    id,
    assignment_id,
    student_id,
    storage_key,
    file_url,
    original_filename,
    mime_type,
    size_bytes,
    text_answer,
    submitted_at,
    status,
    version_number,
    is_latest,
    marks_awarded,
    feedback
  )
  values (
    v_submission_id,
    p_assignment_id,
    v_student_id,
    nullif(p_storage_key, ''),
    nullif(p_file_url, ''),
    nullif(p_original_filename, ''),
    nullif(p_mime_type, ''),
    p_size_bytes,
    v_text_answer,
    now(),
    'submitted',
    v_next_version,
    true,
    null,
    null
  );

  perform public.log_audit_event(
    'assignment_submission.created',
    'assignment_submission',
    v_submission_id::text,
    jsonb_build_object(
      'assignment_id', p_assignment_id,
      'student_id', v_student_id,
      'version_number', v_next_version,
      'file_uploaded', nullif(p_storage_key, '') is not null,
      'text_answer_provided', v_text_answer is not null
    )
  );

  if v_next_version > 1 and nullif(p_storage_key, '') is not null then
    perform public.log_audit_event(
      'assignment_submission.file_replaced',
      'assignment_submission',
      v_submission_id::text,
      jsonb_build_object(
        'assignment_id', p_assignment_id,
        'student_id', v_student_id,
        'version_number', v_next_version
      )
    );
  end if;

  return query select v_submission_id;
end;
$$;

create or replace function public.mark_assignment_submission(
  p_submission_id uuid,
  p_marks_awarded numeric,
  p_feedback text,
  p_status public.submission_status,
  p_rubric_scores jsonb default '{}'::jsonb,
  p_marks_released boolean default false,
  p_feedback_released boolean default false
)
returns setof public.assignment_submissions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_previous public.assignment_submissions%rowtype;
  v_submission public.assignment_submissions%rowtype;
  v_assignment public.assignments%rowtype;
begin
  if not public.can_mark_submission(p_submission_id) then
    raise exception 'submission_marking_not_allowed' using errcode = '42501';
  end if;

  if p_status not in ('submitted', 'marked', 'returned') then
    raise exception 'invalid_submission_status' using errcode = '23514';
  end if;

  if p_marks_awarded is not null and (p_marks_awarded < 0 or p_marks_awarded > 100) then
    raise exception 'marks_out_of_range' using errcode = '23514';
  end if;

  if jsonb_typeof(coalesce(p_rubric_scores, '{}'::jsonb)) <> 'object' then
    raise exception 'invalid_rubric_scores' using errcode = '23514';
  end if;

  select * into v_previous
  from public.assignment_submissions
  where id = p_submission_id;

  if not found then
    raise exception 'submission_not_found' using errcode = 'P0002';
  end if;

  update public.assignment_submissions
  set marks_awarded = p_marks_awarded,
      feedback = nullif(btrim(coalesce(p_feedback, '')), ''),
      status = p_status,
      rubric_scores_json = coalesce(p_rubric_scores, '{}'::jsonb),
      marks_released = coalesce(p_marks_released, false),
      feedback_released = coalesce(p_feedback_released, false),
      released_at = case
        when coalesce(p_marks_released, false) or coalesce(p_feedback_released, false) then coalesce(released_at, now())
        else null
      end
  where id = p_submission_id
  returning * into v_submission;

  if not found then
    raise exception 'submission_not_found' using errcode = 'P0002';
  end if;

  perform public.log_audit_event(
    'submission.marked',
    'assignment_submission',
    v_submission.id::text,
    jsonb_build_object(
      'assignment_id', v_submission.assignment_id,
      'student_id', v_submission.student_id,
      'previous_status', v_previous.status,
      'new_status', v_submission.status,
      'previous_marks_awarded', v_previous.marks_awarded,
      'new_marks_awarded', v_submission.marks_awarded
    )
  );

  if v_previous.feedback is distinct from v_submission.feedback
    or v_previous.rubric_scores_json is distinct from v_submission.rubric_scores_json then
    perform public.log_audit_event(
      'feedback.updated',
      'assignment_submission',
      v_submission.id::text,
      jsonb_build_object(
        'assignment_id', v_submission.assignment_id,
        'student_id', v_submission.student_id,
        'feedback_present', v_submission.feedback is not null,
        'rubric_scores_present', v_submission.rubric_scores_json <> '{}'::jsonb
      )
    );
  end if;

  if (not coalesce(v_previous.marks_released, false) and coalesce(v_submission.marks_released, false))
    or (not coalesce(v_previous.feedback_released, false) and coalesce(v_submission.feedback_released, false)) then
    perform public.log_audit_event(
      'result.released',
      'assignment_submission',
      v_submission.id::text,
      jsonb_build_object(
        'assignment_id', v_submission.assignment_id,
        'student_id', v_submission.student_id,
        'marks_released', v_submission.marks_released,
        'feedback_released', v_submission.feedback_released,
        'released_at', v_submission.released_at
      )
    );
  end if;

  if (coalesce(v_previous.marks_released, false) and not coalesce(v_submission.marks_released, false))
    or (coalesce(v_previous.feedback_released, false) and not coalesce(v_submission.feedback_released, false)) then
    perform public.log_audit_event(
      'result.unreleased',
      'assignment_submission',
      v_submission.id::text,
      jsonb_build_object(
        'assignment_id', v_submission.assignment_id,
        'student_id', v_submission.student_id,
        'marks_released', v_submission.marks_released,
        'feedback_released', v_submission.feedback_released
      )
    );
  end if;

  if p_status = 'marked' and p_marks_awarded is not null then
    select * into v_assignment
    from public.assignments
    where id = v_submission.assignment_id;

    -- Upsert on assignment_submission_id (real bug fix, not a design choice --
    -- see the idx_student_progress_submission_unique comment): re-marking the
    -- same submission must update its existing progress row, not insert a new
    -- one every time the mark changes.
    insert into public.student_progress (
      student_id,
      subject_id,
      topic,
      score,
      cognitive_level,
      recorded_at,
      assignment_submission_id
    )
    values (
      v_submission.student_id,
      v_assignment.subject_id,
      coalesce(v_assignment.title, 'Marked assignment'),
      p_marks_awarded,
      null,
      now(),
      v_submission.id
    )
    on conflict (assignment_submission_id) where assignment_submission_id is not null
    do update set
      student_id = excluded.student_id,
      subject_id = excluded.subject_id,
      topic = excluded.topic,
      score = excluded.score,
      recorded_at = excluded.recorded_at;
  end if;

  return next v_submission;
end;
$$;

create or replace function public.get_student_assignment_submissions()
returns table (
  id uuid,
  assignment_id uuid,
  student_id uuid,
  storage_key text,
  file_url text,
  original_filename text,
  mime_type text,
  size_bytes bigint,
  text_answer text,
  submitted_at timestamptz,
  status public.submission_status,
  version_number integer,
  is_latest boolean,
  marks_awarded numeric,
  feedback text,
  rubric_scores_json jsonb,
  marks_released boolean,
  feedback_released boolean,
  released_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    sub.id,
    sub.assignment_id,
    sub.student_id,
    sub.storage_key,
    sub.file_url,
    sub.original_filename,
    sub.mime_type,
    sub.size_bytes,
    sub.text_answer,
    sub.submitted_at,
    sub.status,
    sub.version_number,
    sub.is_latest,
    case when sub.marks_released then sub.marks_awarded else null end as marks_awarded,
    case when sub.feedback_released then sub.feedback else null end as feedback,
    case when sub.feedback_released then sub.rubric_scores_json else '{}'::jsonb end as rubric_scores_json,
    sub.marks_released,
    sub.feedback_released,
    sub.released_at
  from public.assignment_submissions sub
  where sub.student_id = public.current_student_id()
    order by sub.submitted_at desc;
$$;

create or replace function public.get_parent_progress_reports()
returns table (
  student_id uuid,
  student_name text,
  grade text,
  school text,
  assignment_title text,
  marks_awarded numeric,
  feedback text,
  released_at timestamptz,
  topic text,
  topic_score numeric
)
language sql
security definer
set search_path = public
as $$
  select
    s.id as student_id,
    p.full_name as student_name,
    s.grade,
    s.school,
    a.title as assignment_title,
    sub.marks_awarded,
    case when sub.feedback_released then sub.feedback else null end as feedback,
    sub.released_at,
    sp.topic,
    sp.score as topic_score
  from public.guardians g
  join public.student_guardians sg on sg.guardian_id = g.id
  join public.students s on s.id = sg.student_id
  join public.profiles p on p.id = s.profile_id
  left join public.assignment_submissions sub
    on sub.student_id = s.id
    and sub.marks_released = true
    and sub.marks_awarded is not null
  left join public.assignments a on a.id = sub.assignment_id
  left join lateral (
    select progress.topic, progress.score
    from public.student_progress progress
    where progress.student_id = s.id
    order by progress.recorded_at desc
    limit 1
  ) sp on true
  where public.current_profile_role() = 'parent'
    and g.profile_id = public.current_profile_id()
    and g.status = 'active'
    and sg.status = 'active'
    and sg.can_receive_reports = true
  order by p.full_name, sub.released_at desc nulls last;
$$;

grant execute on function public.submit_assignment_submission(uuid, uuid, text, text, text, text, bigint, text) to authenticated;
grant execute on function public.mark_assignment_submission(uuid, numeric, text, public.submission_status, jsonb, boolean, boolean) to authenticated;
grant execute on function public.get_student_assignment_submissions() to authenticated;
grant execute on function public.get_parent_progress_reports() to authenticated;
revoke execute on function public.log_audit_event(text, text, text, jsonb) from public;
revoke execute on function public.log_audit_event(text, text, text, jsonb) from anon;
revoke execute on function public.log_audit_event(text, text, text, jsonb) from authenticated;
grant execute on function public.record_audit_event(text, text, text, jsonb) to authenticated;

drop policy if exists "profiles_select_self_or_admin" on public.profiles;
create policy "profiles_select_self_or_admin"
on public.profiles for select
using (auth_user_id = auth.uid() or public.is_platform_admin());

drop policy if exists "profiles_select_allocated_learning_relationship" on public.profiles;
create policy "profiles_select_allocated_learning_relationship"
on public.profiles for select
using (
  id in (
    select s.profile_id
    from public.students s
    join public.tutor_student_allocations tsa on tsa.student_id = s.id
    where tsa.tutor_id = public.current_tutor_id()
      and tsa.status = 'active'
  )
  or id in (
    select t.profile_id
    from public.tutors t
    join public.tutor_student_allocations tsa on tsa.tutor_id = t.id
    where tsa.student_id = public.current_student_id()
      and tsa.status = 'active'
  )
);

drop policy if exists "profiles_insert_self_student_or_tutor" on public.profiles;
create policy "profiles_insert_self_student_or_tutor"
on public.profiles for insert
with check (
  auth_user_id = auth.uid()
  and role in ('student', 'tutor', 'parent')
);

drop policy if exists "admin_full_access_profiles" on public.profiles;
create policy "admin_full_access_profiles"
on public.profiles for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "admin_select_audit_log" on public.audit_log;
create policy "admin_select_audit_log"
on public.audit_log for select
using (public.is_platform_admin());

drop policy if exists "no_direct_audit_log_insert" on public.audit_log;
create policy "no_direct_audit_log_insert"
on public.audit_log for insert
with check (false);

drop policy if exists "no_direct_audit_log_update" on public.audit_log;
create policy "no_direct_audit_log_update"
on public.audit_log for update
using (false)
with check (false);

drop policy if exists "no_direct_audit_log_delete" on public.audit_log;
create policy "no_direct_audit_log_delete"
on public.audit_log for delete
using (false);

drop policy if exists "students_select_self_or_admin" on public.students;
create policy "students_select_self_or_admin"
on public.students for select
using (
  public.is_platform_admin()
  or profile_id = public.current_profile_id()
  or id in (
    select tsa.student_id
    from public.tutor_student_allocations tsa
    where tsa.tutor_id = public.current_tutor_id()
      and tsa.status = 'active'
  )
);

-- Raw subqueries on public.profiles here would recurse (see the "Identity
-- lookup shadow table" comment near current_profile_role()); current_profile_id()/
-- current_profile_role() now resolve via public.profile_identities instead.
drop policy if exists "students_insert_self" on public.students;
create policy "students_insert_self"
on public.students for insert
with check (
  profile_id = public.current_profile_id()
  and public.current_profile_role() = 'student'
);

drop policy if exists "admin_full_access_students" on public.students;
create policy "admin_full_access_students"
on public.students for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "guardians_select_scoped" on public.guardians;
create policy "guardians_select_scoped"
on public.guardians for select
using (
  public.is_platform_admin()
  or profile_id = public.current_profile_id()
);

drop policy if exists "admin_manage_guardians" on public.guardians;
create policy "admin_manage_guardians"
on public.guardians for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "student_guardians_select_scoped" on public.student_guardians;
create policy "student_guardians_select_scoped"
on public.student_guardians for select
using (
  public.is_platform_admin()
  or guardian_id in (
    select g.id
    from public.guardians g
    where g.profile_id = public.current_profile_id()
  )
);

drop policy if exists "admin_manage_student_guardians" on public.student_guardians;
create policy "admin_manage_student_guardians"
on public.student_guardians for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

-- Raw joins into public.profiles here would recurse (see the "Identity
-- lookup shadow table" comment near current_profile_role()); current_student_id()
-- now resolves via public.profile_identities instead of public.profiles directly.
drop policy if exists "students_select_own_career_profile" on public.student_career_profiles;
create policy "students_select_own_career_profile"
on public.student_career_profiles for select
using (
  student_id = public.current_student_id()
);

drop policy if exists "students_upsert_own_career_profile" on public.student_career_profiles;
create policy "students_upsert_own_career_profile"
on public.student_career_profiles for all
using (
  student_id = public.current_student_id()
)
with check (
  student_id = public.current_student_id()
);

drop policy if exists "tutors_select_self_or_admin" on public.tutors;
create policy "tutors_select_self_or_admin"
on public.tutors for select
using (
  public.is_platform_admin()
  or profile_id = public.current_profile_id()
  or id in (
    select tsa.tutor_id
    from public.tutor_student_allocations tsa
    where tsa.student_id = public.current_student_id()
      and tsa.status = 'active'
  )
);

-- Raw subqueries on public.profiles here would recurse (see the "Identity
-- lookup shadow table" comment near current_profile_role()); current_profile_id()/
-- current_profile_role() now resolve via public.profile_identities instead.
drop policy if exists "tutors_insert_self_pending" on public.tutors;
create policy "tutors_insert_self_pending"
on public.tutors for insert
with check (
  status = 'pending'
  and profile_id = public.current_profile_id()
  and public.current_profile_role() = 'tutor'
);

drop policy if exists "admin_full_access_tutors" on public.tutors;
create policy "admin_full_access_tutors"
on public.tutors for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "subjects_read_authenticated" on public.subjects;
create policy "subjects_read_authenticated"
on public.subjects for select
using (auth.uid() is not null);

drop policy if exists "admin_manage_subjects" on public.subjects;
create policy "admin_manage_subjects"
on public.subjects for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "tutors_insert_subjects" on public.subjects;
create policy "tutors_insert_subjects"
on public.subjects for insert
with check (public.current_profile_role() = 'tutor');

-- SECURITY (AUDIT.md High, fixed in Phase 2 step 2): the previous
-- "assignments_read_authenticated" policy (using auth.uid() is not null) let
-- ANY authenticated user read ANY assignment -- any status, any org. It is
-- removed here (create statement deleted) and explicitly dropped at the end of
-- this file so existing databases lose it on apply too. Its replacement,
-- "assignments_student_read_published_own_org", scopes student reads to
-- published assignments in their own org. See section 7.4 at the end of this file.

drop policy if exists "admin_manage_assignments" on public.assignments;
create policy "admin_manage_assignments"
on public.assignments for all
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "tutors_manage_own_assignments" on public.assignments;
create policy "tutors_manage_own_assignments"
on public.assignments for all
using (
  public.current_profile_role() = 'tutor'
  and created_by = public.current_profile_id()
)
with check (
  public.current_profile_role() = 'tutor'
  and created_by = public.current_profile_id()
);

drop policy if exists "submissions_student_self_or_admin" on public.assignment_submissions;
create policy "submissions_student_self_or_admin"
on public.assignment_submissions for select
using (
  public.is_platform_admin()
);

drop policy if exists "submissions_student_insert_self" on public.assignment_submissions;
drop policy if exists "submissions_student_update_self" on public.assignment_submissions;
drop policy if exists "submissions_student_mark_previous_versions" on public.assignment_submissions;
drop policy if exists "tutors_update_own_assignment_submissions" on public.assignment_submissions;
drop policy if exists "tutor_insert_progress" on public.student_progress;
-- AUDIT.md Critical (fixed): explicitly drop the permissive student INSERT policy so
-- existing databases lose it on apply, not just fresh builds. See the note further
-- down where this policy's create statement was removed.
drop policy if exists "submissions_student_rpc_insert_shape" on public.assignment_submissions;

drop policy if exists "submissions_student_insert_via_rpc_guard" on public.assignment_submissions;
create policy "submissions_student_insert_via_rpc_guard"
on public.assignment_submissions for insert
with check (
  false
);

drop policy if exists "submissions_no_direct_student_update" on public.assignment_submissions;
create policy "submissions_no_direct_student_update"
on public.assignment_submissions for update
using (
  false
)
with check (
  false
);

drop policy if exists "submissions_tutor_mark_via_rpc_only" on public.assignment_submissions;
create policy "submissions_tutor_mark_via_rpc_only"
on public.assignment_submissions for update
using (
  false
)
with check (
  false
);

-- SECURITY (AUDIT.md Critical, fixed): the previous permissive policy
-- "submissions_student_rpc_insert_shape" allowed students to INSERT directly via
-- PostgREST, bypassing submit_assignment_submission()'s storage-path validation,
-- advisory-lock version sequencing, and log_audit_event() call. Because Postgres
-- ORs permissive INSERT policies together, that shape policy overrode the
-- "with check (false)" guard above and left the RPC's guarantees unenforced.
-- It is removed. The only remaining INSERT policy is
-- "submissions_student_insert_via_rpc_guard" (with check false), so no client can
-- insert a submission row directly; all submissions must go through the
-- SECURITY DEFINER submit_assignment_submission() RPC, which bypasses RLS by
-- design and is the single audited, validated write path. The frontend already
-- calls only this RPC (src/features/assignments/assignmentMutations.ts).

drop policy if exists "admin_manage_submissions" on public.assignment_submissions;
create policy "admin_manage_submissions"
on public.assignment_submissions for all
using (public.is_platform_admin())
with check (public.is_platform_admin());
;
