-- Phase 4: make assignment submission retries idempotent. A stable UUID is
-- generated by the caller before Storage upload and identifies one immutable
-- submission attempt. Replaying the same UUID + payload returns the committed
-- row; reusing it for different work is rejected.

create or replace function public.submit_assignment_submission(
  p_assignment_id uuid,
  p_submission_id uuid,
  p_storage_key text,
  p_file_url text,
  p_original_filename text,
  p_mime_type text,
  p_size_bytes bigint,
  p_text_answer text
)
returns table (submission_id uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_student_id uuid := public.current_student_id();
  v_assignment public.assignments%rowtype;
  v_existing_submission public.assignment_submissions%rowtype;
  v_submission_id uuid := p_submission_id;
  v_next_version integer;
  v_storage_key text := nullif(btrim(coalesce(p_storage_key, '')), '');
  v_file_url text := nullif(btrim(coalesce(p_file_url, '')), '');
  v_original_filename text := nullif(btrim(coalesce(p_original_filename, '')), '');
  v_mime_type text := nullif(btrim(coalesce(p_mime_type, '')), '');
  v_text_answer text := nullif(btrim(coalesce(p_text_answer, '')), '');
begin
  if public.current_profile_role() <> 'student' or v_student_id is null then
    raise exception 'only_students_can_submit' using errcode = '42501';
  end if;
  if v_submission_id is null then
    raise exception 'submission_id_required' using errcode = '23502';
  end if;
  if v_text_answer is null and v_storage_key is null then
    raise exception 'submission_content_required' using errcode = '23514';
  end if;
  if v_storage_key is distinct from v_file_url then
    raise exception 'invalid_submission_file_reference' using errcode = '23514';
  end if;
  if v_storage_key is null
     and (v_original_filename is not null or v_mime_type is not null or p_size_bytes is not null)
  then
    raise exception 'invalid_submission_file_metadata' using errcode = '23514';
  end if;
  if p_size_bytes is not null and p_size_bytes < 0 then
    raise exception 'invalid_submission_file_size' using errcode = '23514';
  end if;
  if v_storage_key is not null
     and v_storage_key !~ ('^' || v_student_id::text || '/' || p_assignment_id::text || '/' || v_submission_id::text || '/submission\.[A-Za-z0-9]+$')
  then
    raise exception 'invalid_submission_storage_path' using errcode = '42501';
  end if;

  -- Serialize both UUID replays and version allocation. The UUID lock protects
  -- against the same attempt being raced across identities/assignments; the
  -- student-assignment lock preserves the one-latest-version invariant.
  perform pg_advisory_xact_lock(
    hashtextextended('assignment-submission-id:' || v_submission_id::text, 0)
  );
  perform pg_advisory_xact_lock(
    hashtextextended('assignment-submission-version:' || p_assignment_id::text || ':' || v_student_id::text, 0)
  );

  select s.* into v_existing_submission
  from public.assignment_submissions s
  where s.id = v_submission_id;

  if found then
    if v_existing_submission.assignment_id <> p_assignment_id
       or v_existing_submission.student_id <> v_student_id
    then
      raise exception 'submission_id_conflict' using errcode = '23505';
    end if;

    if v_existing_submission.storage_key is distinct from v_storage_key
       or v_existing_submission.file_url is distinct from v_file_url
       or v_existing_submission.original_filename is distinct from v_original_filename
       or v_existing_submission.mime_type is distinct from v_mime_type
       or v_existing_submission.size_bytes is distinct from p_size_bytes
       or v_existing_submission.text_answer is distinct from v_text_answer
    then
      raise exception 'submission_retry_payload_mismatch' using errcode = '23505';
    end if;

    -- A prior transaction committed and only its response was lost. Return the
    -- original row without creating a version or duplicating audit events.
    return query select v_existing_submission.id;
    return;
  end if;

  select a.* into v_assignment
  from public.assignments a
  where a.id = p_assignment_id;

  if not found then
    raise exception 'assignment_not_found' using errcode = 'P0002';
  end if;
  if v_assignment.status <> 'published'
     or v_assignment.organization_id is distinct from public.current_student_org_id()
  then
    raise exception 'assignment_not_open_for_submission' using errcode = '42501';
  end if;

  select coalesce(max(s.version_number), 0) + 1
  into v_next_version
  from public.assignment_submissions s
  where s.assignment_id = p_assignment_id
    and s.student_id = v_student_id;

  update public.assignment_submissions
  set is_latest = false
  where assignment_id = p_assignment_id
    and student_id = v_student_id
    and is_latest = true;

  insert into public.assignment_submissions (
    id,
    assignment_id,
    student_id,
    storage_key,
    file_url,
    original_filename,
    mime_type,
    size_bytes,
    text_answer,
    submitted_at,
    status,
    version_number,
    is_latest,
    marks_awarded,
    feedback
  )
  values (
    v_submission_id,
    p_assignment_id,
    v_student_id,
    v_storage_key,
    v_file_url,
    v_original_filename,
    v_mime_type,
    p_size_bytes,
    v_text_answer,
    now(),
    'submitted',
    v_next_version,
    true,
    null,
    null
  );

  perform public.log_audit_event(
    'assignment_submission.created',
    'assignment_submission',
    v_submission_id::text,
    jsonb_build_object(
      'assignment_id', p_assignment_id,
      'student_id', v_student_id,
      'version_number', v_next_version,
      'file_uploaded', v_storage_key is not null,
      'text_answer_provided', v_text_answer is not null
    )
  );

  if v_next_version > 1 and v_storage_key is not null then
    perform public.log_audit_event(
      'assignment_submission.file_replaced',
      'assignment_submission',
      v_submission_id::text,
      jsonb_build_object(
        'assignment_id', p_assignment_id,
        'student_id', v_student_id,
        'version_number', v_next_version
      )
    );
  end if;

  return query select v_submission_id;
end;
$$;

revoke execute on function public.submit_assignment_submission(uuid, uuid, text, text, text, text, bigint, text) from public;
revoke execute on function public.submit_assignment_submission(uuid, uuid, text, text, text, text, bigint, text) from anon;
grant execute on function public.submit_assignment_submission(uuid, uuid, text, text, text, text, bigint, text) to authenticated;;
